export interface ComputingCenter {
  id: string;
  name: string;
  province: string;
  district: string;
  longitude: number;
  latitude: number;
  chipType: string;
  chipCount: number;
}

export interface ProvinceGroup {
  province: string;
  centers: ComputingCenter[];
}

export const data: ProvinceGroup[] = [
  {
    province: "上海",
    centers: [
      {
        id: "shanghai-pudong-1",
        name: "上海浦东数据中心1号",
        province: "上海",
        district: "浦东新区",
        longitude: 121.5444,
        latitude: 31.2189,
        chipType: "英伟达 H100",
        chipCount: 1800,
      },
      {
        id: "shanghai-xuhui-1",
        name: "上海徐汇数据中心1号",
        province: "上海",
        district: "徐汇区",
        longitude: 121.4367,
        latitude: 31.1882,
        chipType: "英伟达 A100",
        chipCount: 1200,
      },
      {
        id: "shanghai-jiading-1",
        name: "上海嘉定数据中心1号",
        province: "上海",
        district: "嘉定区",
        longitude: 121.2506,
        latitude: 31.3756,
        chipType: "华为昇腾910",
        chipCount: 1500,
      },
      {
        id: "shanghai-songjiang-1",
        name: "上海松江数据中心1号",
        province: "上海",
        district: "松江区",
        longitude: 121.2234,
        latitude: 31.0306,
        chipType: "英伟达 H100",
        chipCount: 1600,
      },
      {
        id: "shanghai-qingpu-1",
        name: "上海青浦数据中心1号",
        province: "上海",
        district: "青浦区",
        longitude: 121.1242,
        latitude: 31.1438,
        chipType: "寒武纪MLU370",
        chipCount: 600,
      },
    ],
  },
  {
    province: "江苏",
    centers: [
      {
        id: "jiangsu-nanjing-1",
        name: "南京数据中心1号",
        province: "江苏",
        district: "鼓楼区",
        longitude: 118.7969,
        latitude: 32.0603,
        chipType: "英伟达 A100",
        chipCount: 1100,
      },
      {
        id: "jiangsu-nanjing-2",
        name: "南京数据中心2号",
        province: "江苏",
        district: "江宁区",
        longitude: 118.7222,
        latitude: 32.0417,
        chipType: "华为昇腾910",
        chipCount: 900,
      },
      {
        id: "jiangsu-suzhou-1",
        name: "苏州数据中心1号",
        province: "江苏",
        district: "工业园区",
        longitude: 120.5853,
        latitude: 31.2989,
        chipType: "英伟达 H100",
        chipCount: 1400,
      },
    ],
  },
  {
    province: "浙江",
    centers: [
      {
        id: "zhejiang-hangzhou-1",
        name: "杭州数据中心1号",
        province: "浙江",
        district: "西湖区",
        longitude: 120.1551,
        latitude: 30.2741,
        chipType: "英伟达 A100",
        chipCount: 1000,
      },
      {
        id: "zhejiang-hangzhou-2",
        name: "杭州数据中心2号",
        province: "浙江",
        district: "滨江区",
        longitude: 120.1903,
        latitude: 30.2477,
        chipType: "英伟达 H100",
        chipCount: 1200,
      },
      {
        id: "zhejiang-ningbo-1",
        name: "宁波数据中心1号",
        province: "浙江",
        district: "鄞州区",
        longitude: 121.5494,
        latitude: 29.8683,
        chipType: "华为昇腾910",
        chipCount: 800,
      },
    ],
  },
  {
    province: "北京",
    centers: [
      {
        id: "beijing-haidian-1",
        name: "北京海淀区数据中心1号",
        province: "北京",
        district: "海淀区",
        longitude: 116.2982,
        latitude: 39.9599,
        chipType: "英伟达 H100",
        chipCount: 2000,
      },
      {
        id: "beijing-chaoyang-1",
        name: "北京朝阳区数据中心1号",
        province: "北京",
        district: "朝阳区",
        longitude: 116.4431,
        latitude: 39.9211,
        chipType: "英伟达 A100",
        chipCount: 1400,
      },
      {
        id: "beijing-daxing-1",
        name: "北京大兴区数据中心1号",
        province: "北京",
        district: "大兴区",
        longitude: 116.338,
        latitude: 39.7289,
        chipType: "华为昇腾910",
        chipCount: 1000,
      },
    ],
  },
  {
    province: "广东",
    centers: [
      {
        id: "guangdong-guangzhou-1",
        name: "广州数据中心1号",
        province: "广东",
        district: "天河区",
        longitude: 113.2644,
        latitude: 23.1291,
        chipType: "英伟达 A100",
        chipCount: 1300,
      },
      {
        id: "guangdong-guangzhou-2",
        name: "广州数据中心2号",
        province: "广东",
        district: "黄埔区",
        longitude: 113.2903,
        latitude: 23.1567,
        chipType: "华为昇腾910",
        chipCount: 1000,
      },
      {
        id: "guangdong-shenzhen-1",
        name: "深圳数据中心1号",
        province: "广东",
        district: "南山区",
        longitude: 114.0579,
        latitude: 22.5431,
        chipType: "英伟达 H100",
        chipCount: 1900,
      },
    ],
  },
  {
    province: "湖北",
    centers: [
      {
        id: "hubei-wuhan-1",
        name: "武汉数据中心1号",
        province: "湖北",
        district: "洪山区",
        longitude: 114.3054,
        latitude: 30.5931,
        chipType: "英伟达 A100",
        chipCount: 900,
      },
      {
        id: "hubei-wuhan-2",
        name: "武汉数据中心2号",
        province: "湖北",
        district: "江夏区",
        longitude: 114.2713,
        latitude: 30.6289,
        chipType: "华为昇腾910",
        chipCount: 700,
      },
    ],
  },
  {
    province: "湖南",
    centers: [
      {
        id: "hunan-changsha-1",
        name: "长沙数据中心1号",
        province: "湖南",
        district: "岳麓区",
        longitude: 112.9388,
        latitude: 28.2282,
        chipType: "英伟达 A100",
        chipCount: 800,
      },
      {
        id: "hunan-changsha-2",
        name: "长沙数据中心2号",
        province: "湖南",
        district: "雨花区",
        longitude: 112.9717,
        latitude: 28.1925,
        chipType: "华为昇腾910",
        chipCount: 600,
      },
    ],
  },
  {
    province: "河北",
    centers: [
      {
        id: "hebei-shijiazhuang-1",
        name: "石家庄数据中心1号",
        province: "河北",
        district: "裕华区",
        longitude: 114.5149,
        latitude: 38.0423,
        chipType: "华为昇腾910",
        chipCount: 700,
      },
      {
        id: "hebei-xiongan-1",
        name: "雄安新区数据中心1号",
        province: "河北",
        district: "雄安新区",
        longitude: 115.9957,
        latitude: 38.9768,
        chipType: "寒武纪MLU370",
        chipCount: 400,
      },
    ],
  },
  {
    province: "内蒙古",
    centers: [
      {
        id: "neimenggu-hohhot-1",
        name: "呼和浩特数据中心1号",
        province: "内蒙古",
        district: "新城区",
        longitude: 111.7492,
        latitude: 40.8426,
        chipType: "寒武纪MLU370",
        chipCount: 500,
      },
      {
        id: "neimenggu-baotou-1",
        name: "包头数据中心1号",
        province: "内蒙古",
        district: "青山区",
        longitude: 109.8403,
        latitude: 40.6574,
        chipType: "华为昇腾910",
        chipCount: 600,
      },
    ],
  },
  {
    province: "新疆",
    centers: [
      {
        id: "xinjiang-urumqi-1",
        name: "乌鲁木齐数据中心1号",
        province: "新疆",
        district: "天山区",
        longitude: 87.6168,
        latitude: 43.8256,
        chipType: "寒武纪MLU370",
        chipCount: 300,
      },
      {
        id: "xinjiang-urumqi-2",
        name: "乌鲁木齐数据中心2号",
        province: "新疆",
        district: "沙依巴克区",
        longitude: 87.5843,
        latitude: 43.8592,
        chipType: "华为昇腾910",
        chipCount: 400,
      },
    ],
  },
  {
    province: "宁夏",
    centers: [
      {
        id: "ningxia-yinchuan-1",
        name: "银川数据中心1号",
        province: "宁夏",
        district: "金凤区",
        longitude: 106.2309,
        latitude: 38.4872,
        chipType: "寒武纪MLU370",
        chipCount: 350,
      },
      {
        id: "ningxia-yinchuan-2",
        name: "银川数据中心2号",
        province: "宁夏",
        district: "兴庆区",
        longitude: 106.2547,
        latitude: 38.5118,
        chipType: "华为昇腾910",
        chipCount: 450,
      },
    ],
  },
  {
    province: "青海",
    centers: [
      {
        id: "qinghai-xining-1",
        name: "西宁数据中心1号",
        province: "青海",
        district: "城中区",
        longitude: 101.7782,
        latitude: 36.6171,
        chipType: "寒武纪MLU370",
        chipCount: 250,
      },
      {
        id: "qinghai-xining-2",
        name: "西宁数据中心2号",
        province: "青海",
        district: "城西区",
        longitude: 101.8017,
        latitude: 36.5934,
        chipType: "寒武纪MLU370",
        chipCount: 280,
      },
    ],
  },
];

export function aggregateByProvince(groups: ProvinceGroup[]) {
  return groups.map((g) => ({
    name: g.province,
    value: g.centers.reduce((sum, c) => sum + c.chipCount, 0),
  }));
}

const realData = [
  {
    cluster_name: "云赛数海科技松江大数据计算中心",
    chip_type: "昇腾",
    latitude: "31.04\r",
    card_quantity: "16552",
    region_city: "松江",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 25,
    region: "1",
    colony_type: "全国产卡",
    status: "是",
    longitude: "121.23\r",
  },
  {
    cluster_name: "商汤智算集群",
    chip_type: "英伟达",
    latitude: "30.87\r",
    card_quantity: "54230",
    region_city: "临港",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 26,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.81\r",
  },
  {
    cluster_name: "临港智算集群",
    chip_type: "昇腾、英伟达",
    latitude: "30.9\r",
    card_quantity: "11136",
    region_city: "临港",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 27,
    region: "1",
    colony_type: "NV+国产",
    status: "是",
    longitude: "121.91\r",
  },
  {
    cluster_name: "腾讯长三角人工智能先进计算中心",
    chip_type: "英伟达",
    latitude: "30.99\r",
    card_quantity: "47736",
    region_city: "松江",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 28,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.24\r",
  },
  {
    cluster_name: "有孚上海云计算数据中心",
    chip_type: "英伟达",
    latitude: "31.23\r",
    card_quantity: "10000",
    region_city: "浦东",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 29,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.55\r",
  },
  {
    cluster_name: "优刻得青浦智算中心",
    chip_type: "英伟达",
    latitude: "31.16\r",
    card_quantity: "10000",
    region_city: "青浦",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 30,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.13\r",
  },
  {
    cluster_name: "之江实验室万卡集群",
    chip_type: "英伟达",
    latitude: "30.25\r",
    card_quantity: "10000",
    region_city: "杭州",
    full_name_of_prov: "浙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "浙江",
    id: 40,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "120.22\r",
  },
  {
    cluster_name: "长三角·平湖润泽国际信息港（一期）",
    chip_type: "英伟达",
    latitude: "30.68\r",
    card_quantity: "25000",
    region_city: "平湖",
    full_name_of_prov: "浙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "浙江",
    id: 41,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.02\r",
  },
  {
    cluster_name: "湖南磐云新一代人工智能算力服务中心",
    chip_type: "英伟达",
    latitude: "28.23\r",
    card_quantity: "12000",
    region_city: "长沙",
    full_name_of_prov: "湖南省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "湖南",
    id: 49,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "112.95\r",
  },
  {
    cluster_name: "科大讯飞-飞星一号",
    chip_type: "昇腾",
    latitude: "31.83\r",
    card_quantity: "10240",
    region_city: "合肥",
    full_name_of_prov: "安徽省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "安徽",
    id: 57,
    region: "1",
    colony_type: "全国产卡",
    status: "是",
    longitude: "117.23\r",
  },
  {
    cluster_name: "华为云华东数据中心",
    chip_type: "昇腾",
    latitude: "31.36\r",
    card_quantity: "31914",
    region_city: "芜湖",
    full_name_of_prov: "安徽省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "安徽",
    id: 59,
    region: "1",
    colony_type: "全国产卡",
    status: "是",
    longitude: "118.44\r",
  },
  {
    cluster_name: "腾讯仪征东升云计算数据中心",
    chip_type: "英伟达",
    latitude: "32.4\r",
    card_quantity: "94437",
    region_city: "扬州",
    full_name_of_prov: "江苏省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "江苏",
    id: 62,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "119.42\r",
  },
  {
    cluster_name: "南京江宁腾讯DC",
    chip_type: "英伟达",
    latitude: "32.06",
    card_quantity: "72808",
    region_city: "南京",
    full_name_of_prov: "江苏省",
    built_computing_power: "15000",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "江苏",
    id: 63,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "118.8",
  },
  {
    cluster_name: "长三角·平湖润泽国际信息港（二期）",
    chip_type: "英伟达",
    latitude: "30.78\r",
    card_quantity: "32500",
    region_city: "平湖",
    full_name_of_prov: "浙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "浙江",
    id: 64,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.42\r",
  },
  {
    cluster_name: "中国移动长三角（扬州）数据中心",
    chip_type: "英伟达、昇腾",
    latitude: "32.3\r",
    card_quantity: "16400",
    region_city: "扬州",
    full_name_of_prov: "江苏省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "江苏",
    id: 67,
    region: "1",
    colony_type: "NV+国产",
    status: "是",
    longitude: "119.02\r",
  },
  {
    cluster_name: "京津冀大数据产业园数据中心",
    chip_type: "昇腾",
    latitude: "39.39\r",
    card_quantity: "10980",
    region_city: "武清",
    full_name_of_prov: "天津市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "天津",
    id: 31,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "117.05\r",
  },
  {
    cluster_name: "中国移动（呼和浩特）数据中心",
    chip_type: "英伟达、昇腾、燧原、天数智芯、寒武纪",
    latitude: "40.85\r",
    card_quantity: "18000",
    region_city: "呼和浩特",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 37,
    region: "2",
    colony_type: "NV+国产",
    status: "是",
    longitude: "111.76\r",
  },
  {
    cluster_name: "优刻得内蒙智算中心",
    chip_type: "英伟达",
    latitude: "41\r",
    card_quantity: "20000",
    region_city: "乌兰察布",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 38,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "113.14\r",
  },
  {
    cluster_name: "阿里巴巴乌兰察布开发区数据中心",
    chip_type: "英伟达、AMD",
    latitude: "40.97\r",
    card_quantity: "15000",
    region_city: "乌兰察布",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 39,
    region: "2",
    colony_type: "NV+AMD",
    status: "是",
    longitude: "113.17\r",
  },
  {
    cluster_name: "中国科学院计算机网络信息中心",
    chip_type: "海光",
    latitude: "39.97\r",
    card_quantity: "10000",
    region_city: "海淀",
    full_name_of_prov: "北京市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "北京",
    id: 42,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "116.31\r",
  },
  {
    cluster_name: "联通（怀来）大数据创新产业园",
    chip_type: "英伟达",
    latitude: "40.77\r",
    card_quantity: "32000",
    region_city: "张家口",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 43,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "114.89\r",
  },
  {
    cluster_name: "亿广云数据中心",
    chip_type: "英伟达",
    latitude: "39.89\r",
    card_quantity: "13600",
    region_city: "秦皇岛",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 44,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "119.53\r",
  },
  {
    cluster_name: "润泽（廊坊）国际信息港数据中心",
    chip_type: "昇腾、英伟达",
    latitude: "39.54\r",
    card_quantity: "32000",
    region_city: "廊坊",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 45,
    region: "2",
    colony_type: "NV+国产",
    status: "是",
    longitude: "116.69\r",
  },
  {
    cluster_name: "智联网云交换中心一期",
    chip_type: "昇腾",
    latitude: "39.51\r",
    card_quantity: "17000",
    region_city: "廊坊",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 46,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "116.72\r",
  },
  {
    cluster_name: "智联网云交换中心二期",
    chip_type: "昇腾",
    latitude: "39.58\r",
    card_quantity: "17620",
    region_city: "廊坊",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 47,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "116.68\r",
  },
  {
    cluster_name: "世纪互联华北云计算中心",
    chip_type: "英伟达",
    latitude: "40.76\r",
    card_quantity: "12256",
    region_city: "张家口",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 48,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "114.89\r",
  },
  {
    cluster_name: "百度云计算（阳泉）中心",
    chip_type: "昆仑芯",
    latitude: "37.86\r",
    card_quantity: "40000",
    region_city: "阳泉",
    full_name_of_prov: "山西省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "山西",
    id: 60,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "113.59\r",
  },
  {
    cluster_name: "张家口明蔚京西云计算数据中心项目（一期）",
    chip_type: "寒武纪",
    latitude: "40.77\r",
    card_quantity: "108852",
    region_city: "张家口",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 65,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "114.99\r",
  },
  {
    cluster_name: "科大讯飞-飞星二号（涉密）",
    chip_type: "昇腾",
    latitude: "40.35\r",
    card_quantity: "10240",
    region_city: "呼和浩特",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 66,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "111.36\r",
  },
  {
    cluster_name: "中国移动哈尔滨智算集群",
    chip_type: "昇腾",
    latitude: "45.81\r",
    card_quantity: "18432",
    region_city: "哈尔滨",
    full_name_of_prov: "黑龙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "黑龙江",
    id: 32,
    region: "3",
    colony_type: "全国产卡",
    status: "是",
    longitude: "126.54\r",
  },
  {
    cluster_name: "中国电信“东数西算”国家枢纽庆阳算力中心",
    chip_type: "燧原、英伟达、昇腾",
    latitude: "35.72\r",
    card_quantity: "21160",
    region_city: "庆阳",
    full_name_of_prov: "甘肃省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "甘肃",
    id: 33,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "107.65\r",
  },
  {
    cluster_name: "中国移动（甘肃·庆阳）数据中心",
    chip_type: "燧原、英伟达",
    latitude: "35.7\r",
    card_quantity: "10016",
    region_city: "庆阳",
    full_name_of_prov: "甘肃省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "甘肃",
    id: 34,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "107.64\r",
  },
  {
    cluster_name: "碳和液冷数据中心",
    chip_type: "英伟达",
    latitude: "45.59\r",
    card_quantity: "11000",
    region_city: "克拉玛依",
    full_name_of_prov: "新疆维吾尔自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "新疆",
    id: 50,
    region: "4",
    colony_type: "全NV卡",
    status: "是",
    longitude: "84.6\r",
  },
  {
    cluster_name: "克融云智算中心一期",
    chip_type: "英伟达",
    latitude: "45.53\r",
    card_quantity: "16000",
    region_city: "克拉玛依",
    full_name_of_prov: "新疆维吾尔自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "新疆",
    id: 51,
    region: "4",
    colony_type: "全NV卡",
    status: "是",
    longitude: "84.9\r",
  },
  {
    cluster_name: "丝路新云绿色算力中心",
    chip_type: "英伟达",
    latitude: "45.6\r",
    card_quantity: "16528",
    region_city: "克拉玛依",
    full_name_of_prov: "新疆维吾尔自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "新疆",
    id: 52,
    region: "4",
    colony_type: "全NV卡",
    status: "是",
    longitude: "83.88\r",
  },
  {
    cluster_name: "中国联通中卫云数据中心",
    chip_type: "昆仑芯",
    latitude: "37.51\r",
    card_quantity: "14312",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 53,
    region: "4",
    colony_type: "全国产卡",
    status: "是",
    longitude: "105.2\r",
  },
  {
    cluster_name: "中国联通中卫云数据中心",
    chip_type: "昆仑芯",
    latitude: "37.48\r",
    card_quantity: "32000",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 54,
    region: "4",
    colony_type: "全国产卡",
    status: "是",
    longitude: "105.19\r",
  },
  {
    cluster_name: "中国移动（宁夏中卫）数据中心",
    chip_type: "昇腾、英伟达",
    latitude: "37.53\r",
    card_quantity: "15200",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 55,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "105.2\r",
  },
  {
    cluster_name: "中国联通中卫云数据中心",
    chip_type: "昇腾",
    latitude: "37.52\r",
    card_quantity: "20000",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 56,
    region: "4",
    colony_type: "全国产卡",
    status: "是",
    longitude: "105.23\r",
  },
  {
    cluster_name: "中国联通三江源绿电智算融合示范园三期",
    chip_type: "平头哥、英伟达",
    latitude: "36.62\r",
    card_quantity: "12288",
    region_city: "西宁",
    full_name_of_prov: "青海省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "青海",
    id: 61,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "101.78\r",
  },
  {
    cluster_name: "华为云上屯云数据中心",
    chip_type: "昇腾",
    latitude: "26.44\r",
    card_quantity: "47000",
    region_city: "贵安新区",
    full_name_of_prov: "贵州省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "贵州",
    id: 35,
    region: "5",
    colony_type: "全国产卡",
    status: "是",
    longitude: "106.5\r",
  },
  {
    cluster_name: "华为云高端园数据中心",
    chip_type: "昇腾",
    latitude: "26.47\r",
    card_quantity: "160000",
    region_city: "贵安新区",
    full_name_of_prov: "贵州省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "贵州",
    id: 36,
    region: "5",
    colony_type: "全国产卡",
    status: "是",
    longitude: "106.49\r",
  },
];
