export interface ClusterData {
  cluster_name: string;
  chip_type: string;
  latitude: string;
  longitude: string;
  card_quantity: string;
  region_city: string;
  full_name_of_prov: string;
  built_computing_power: string;
  suanli_type: string;
  suanli: string;
  region_prov: string;
  id: number;
  region: string;
  colony_type: string;
  status: string;
}

export const realData: ClusterData[] = [
  {
    cluster_name: "云赛数海科技松江大数据计算中心",
    chip_type: "昇腾",
    latitude: "31.04",
    card_quantity: "16552",
    region_city: "松江",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 25,
    region: "1",
    colony_type: "全国产卡",
    status: "是",
    longitude: "121.23",
  },
  {
    cluster_name: "商汤智算集群",
    chip_type: "英伟达",
    latitude: "30.87",
    card_quantity: "54230",
    region_city: "临港",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 26,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.81",
  },
  {
    cluster_name: "临港智算集群",
    chip_type: "昇腾、英伟达",
    latitude: "30.9",
    card_quantity: "11136",
    region_city: "临港",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 27,
    region: "1",
    colony_type: "NV+国产",
    status: "是",
    longitude: "121.91",
  },
  {
    cluster_name: "腾讯长三角人工智能先进计算中心",
    chip_type: "英伟达",
    latitude: "30.99",
    card_quantity: "47736",
    region_city: "松江",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 28,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.24",
  },
  {
    cluster_name: "有孚上海云计算数据中心",
    chip_type: "英伟达",
    latitude: "31.23",
    card_quantity: "10000",
    region_city: "浦东",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 29,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.55",
  },
  {
    cluster_name: "优刻得青浦智算中心",
    chip_type: "英伟达",
    latitude: "31.16",
    card_quantity: "10000",
    region_city: "青浦",
    full_name_of_prov: "上海市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "上海",
    id: 30,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.13",
  },
  {
    cluster_name: "之江实验室万卡集群",
    chip_type: "英伟达",
    latitude: "30.25",
    card_quantity: "10000",
    region_city: "杭州",
    full_name_of_prov: "浙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "浙江",
    id: 40,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "120.22",
  },
  {
    cluster_name: "长三角·平湖润泽国际信息港（一期）",
    chip_type: "英伟达",
    latitude: "30.68",
    card_quantity: "25000",
    region_city: "平湖",
    full_name_of_prov: "浙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "浙江",
    id: 41,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.02",
  },
  {
    cluster_name: "湖南磐云新一代人工智能算力服务中心",
    chip_type: "英伟达",
    latitude: "28.23",
    card_quantity: "12000",
    region_city: "长沙",
    full_name_of_prov: "湖南省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "湖南",
    id: 49,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "112.95",
  },
  {
    cluster_name: "科大讯飞-飞星一号",
    chip_type: "昇腾",
    latitude: "31.83",
    card_quantity: "10240",
    region_city: "合肥",
    full_name_of_prov: "安徽省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "安徽",
    id: 57,
    region: "1",
    colony_type: "全国产卡",
    status: "是",
    longitude: "117.23",
  },
  {
    cluster_name: "华为云华东数据中心",
    chip_type: "昇腾",
    latitude: "31.36",
    card_quantity: "31914",
    region_city: "芜湖",
    full_name_of_prov: "安徽省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "安徽",
    id: 59,
    region: "1",
    colony_type: "全国产卡",
    status: "是",
    longitude: "118.44",
  },
  {
    cluster_name: "腾讯仪征东升云计算数据中心",
    chip_type: "英伟达",
    latitude: "32.4",
    card_quantity: "94437",
    region_city: "扬州",
    full_name_of_prov: "江苏省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "江苏",
    id: 62,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "119.42",
  },
  {
    cluster_name: "南京江宁腾讯DC",
    chip_type: "英伟达",
    latitude: "32.06",
    card_quantity: "72808",
    region_city: "南京",
    full_name_of_prov: "江苏省",
    built_computing_power: "15000",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "江苏",
    id: 63,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "118.8",
  },
  {
    cluster_name: "长三角·平湖润泽国际信息港（二期）",
    chip_type: "英伟达",
    latitude: "30.78",
    card_quantity: "32500",
    region_city: "平湖",
    full_name_of_prov: "浙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "浙江",
    id: 64,
    region: "1",
    colony_type: "全NV卡",
    status: "是",
    longitude: "121.42",
  },
  {
    cluster_name: "中国移动长三角（扬州）数据中心",
    chip_type: "英伟达、昇腾",
    latitude: "32.3",
    card_quantity: "16400",
    region_city: "扬州",
    full_name_of_prov: "江苏省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "江苏",
    id: 67,
    region: "1",
    colony_type: "NV+国产",
    status: "是",
    longitude: "119.02",
  },
  {
    cluster_name: "京津冀大数据产业园数据中心",
    chip_type: "昇腾",
    latitude: "39.39",
    card_quantity: "10980",
    region_city: "武清",
    full_name_of_prov: "天津市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "天津",
    id: 31,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "117.05",
  },
  {
    cluster_name: "中国移动（呼和浩特）数据中心",
    chip_type: "英伟达、昇腾、燧原、天数智芯、寒武纪",
    latitude: "40.85",
    card_quantity: "18000",
    region_city: "呼和浩特",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 37,
    region: "2",
    colony_type: "NV+国产",
    status: "是",
    longitude: "111.76",
  },
  {
    cluster_name: "优刻得内蒙智算中心",
    chip_type: "英伟达",
    latitude: "41",
    card_quantity: "20000",
    region_city: "乌兰察布",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 38,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "113.14",
  },
  {
    cluster_name: "阿里巴巴乌兰察布开发区数据中心",
    chip_type: "英伟达、AMD",
    latitude: "40.97",
    card_quantity: "15000",
    region_city: "乌兰察布",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 39,
    region: "2",
    colony_type: "NV+AMD",
    status: "是",
    longitude: "113.17",
  },
  {
    cluster_name: "中国科学院计算机网络信息中心",
    chip_type: "海光",
    latitude: "39.97",
    card_quantity: "10000",
    region_city: "海淀",
    full_name_of_prov: "北京市",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "北京",
    id: 42,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "116.31",
  },
  {
    cluster_name: "联通（怀来）大数据创新产业园",
    chip_type: "英伟达",
    latitude: "40.77",
    card_quantity: "32000",
    region_city: "张家口",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 43,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "114.89",
  },
  {
    cluster_name: "亿广云数据中心",
    chip_type: "英伟达",
    latitude: "39.89",
    card_quantity: "13600",
    region_city: "秦皇岛",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 44,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "119.53",
  },
  {
    cluster_name: "润泽（廊坊）国际信息港数据中心",
    chip_type: "昇腾、英伟达",
    latitude: "39.54",
    card_quantity: "32000",
    region_city: "廊坊",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 45,
    region: "2",
    colony_type: "NV+国产",
    status: "是",
    longitude: "116.69",
  },
  {
    cluster_name: "智联网云交换中心一期",
    chip_type: "昇腾",
    latitude: "39.51",
    card_quantity: "17000",
    region_city: "廊坊",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 46,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "116.72",
  },
  {
    cluster_name: "智联网云交换中心二期",
    chip_type: "昇腾",
    latitude: "39.58",
    card_quantity: "17620",
    region_city: "廊坊",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 47,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "116.68",
  },
  {
    cluster_name: "世纪互联华北云计算中心",
    chip_type: "英伟达",
    latitude: "40.76",
    card_quantity: "12256",
    region_city: "张家口",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 48,
    region: "2",
    colony_type: "全NV卡",
    status: "是",
    longitude: "114.89",
  },
  {
    cluster_name: "百度云计算（阳泉）中心",
    chip_type: "昆仑芯",
    latitude: "37.86",
    card_quantity: "40000",
    region_city: "阳泉",
    full_name_of_prov: "山西省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "山西",
    id: 60,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "113.59",
  },
  {
    cluster_name: "张家口明蔚京西云计算数据中心项目（一期）",
    chip_type: "寒武纪",
    latitude: "40.77",
    card_quantity: "108852",
    region_city: "张家口",
    full_name_of_prov: "河北省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "河北",
    id: 65,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "114.99",
  },
  {
    cluster_name: "科大讯飞-飞星二号（涉密）",
    chip_type: "昇腾",
    latitude: "40.35",
    card_quantity: "10240",
    region_city: "呼和浩特",
    full_name_of_prov: "内蒙古自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "内蒙古",
    id: 66,
    region: "2",
    colony_type: "全国产卡",
    status: "是",
    longitude: "111.36",
  },
  {
    cluster_name: "中国移动哈尔滨智算集群",
    chip_type: "昇腾",
    latitude: "45.81",
    card_quantity: "18432",
    region_city: "哈尔滨",
    full_name_of_prov: "黑龙江省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "黑龙江",
    id: 32,
    region: "3",
    colony_type: "全国产卡",
    status: "是",
    longitude: "126.54",
  },
  {
    cluster_name: "中国电信“东数西算”国家枢纽庆阳算力中心",
    chip_type: "燧原、英伟达、昇腾",
    latitude: "35.72",
    card_quantity: "21160",
    region_city: "庆阳",
    full_name_of_prov: "甘肃省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "甘肃",
    id: 33,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "107.65",
  },
  {
    cluster_name: "中国移动（甘肃·庆阳）数据中心",
    chip_type: "燧原、英伟达",
    latitude: "35.7",
    card_quantity: "10016",
    region_city: "庆阳",
    full_name_of_prov: "甘肃省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "甘肃",
    id: 34,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "107.64",
  },
  {
    cluster_name: "碳和液冷数据中心",
    chip_type: "英伟达",
    latitude: "45.59",
    card_quantity: "11000",
    region_city: "克拉玛依",
    full_name_of_prov: "新疆维吾尔自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "新疆",
    id: 50,
    region: "4",
    colony_type: "全NV卡",
    status: "是",
    longitude: "84.6",
  },
  {
    cluster_name: "克融云智算中心一期",
    chip_type: "英伟达",
    latitude: "45.53",
    card_quantity: "16000",
    region_city: "克拉玛依",
    full_name_of_prov: "新疆维吾尔自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "新疆",
    id: 51,
    region: "4",
    colony_type: "全NV卡",
    status: "是",
    longitude: "84.9",
  },
  {
    cluster_name: "丝路新云绿色算力中心",
    chip_type: "英伟达",
    latitude: "45.6",
    card_quantity: "16528",
    region_city: "克拉玛依",
    full_name_of_prov: "新疆维吾尔自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "新疆",
    id: 52,
    region: "4",
    colony_type: "全NV卡",
    status: "是",
    longitude: "83.88",
  },
  {
    cluster_name: "中国联通中卫云数据中心",
    chip_type: "昆仑芯",
    latitude: "37.51",
    card_quantity: "14312",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 53,
    region: "4",
    colony_type: "全国产卡",
    status: "是",
    longitude: "105.2",
  },
  {
    cluster_name: "中国联通中卫云数据中心",
    chip_type: "昆仑芯",
    latitude: "37.48",
    card_quantity: "32000",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 54,
    region: "4",
    colony_type: "全国产卡",
    status: "是",
    longitude: "105.19",
  },
  {
    cluster_name: "中国移动（宁夏中卫）数据中心",
    chip_type: "昇腾、英伟达",
    latitude: "37.53",
    card_quantity: "15200",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 55,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "105.2",
  },
  {
    cluster_name: "中国联通中卫云数据中心",
    chip_type: "昇腾",
    latitude: "37.52",
    card_quantity: "20000",
    region_city: "中卫",
    full_name_of_prov: "宁夏回族自治区",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "宁夏",
    id: 56,
    region: "4",
    colony_type: "全国产卡",
    status: "是",
    longitude: "105.23",
  },
  {
    cluster_name: "中国联通三江源绿电智算融合示范园三期",
    chip_type: "平头哥、英伟达",
    latitude: "36.62",
    card_quantity: "12288",
    region_city: "西宁",
    full_name_of_prov: "青海省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "青海",
    id: 61,
    region: "4",
    colony_type: "NV+国产",
    status: "是",
    longitude: "101.78",
  },
  {
    cluster_name: "华为云上屯云数据中心",
    chip_type: "昇腾",
    latitude: "26.44",
    card_quantity: "47000",
    region_city: "贵安新区",
    full_name_of_prov: "贵州省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "贵州",
    id: 35,
    region: "5",
    colony_type: "全国产卡",
    status: "是",
    longitude: "106.5",
  },
  {
    cluster_name: "华为云高端园数据中心",
    chip_type: "昇腾",
    latitude: "26.47",
    card_quantity: "160000",
    region_city: "贵安新区",
    full_name_of_prov: "贵州省",
    built_computing_power: "",
    suanli_type: "3",
    suanli: "10001及以上",
    region_prov: "贵州",
    id: 36,
    region: "5",
    colony_type: "全国产卡",
    status: "是",
    longitude: "106.49",
  },
];
