/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeployDistrivutionRouteImport } from './routes/deploy/distrivution'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployDistrivutionRoute = DeployDistrivutionRouteImport.update({
  id: '/distrivution',
  path: '/distrivution',
  getParentRoute: () => DeployRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deploy/distrivution': typeof DeployDistrivutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deploy/distrivution': typeof DeployDistrivutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deploy/distrivution': typeof DeployDistrivutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deploy/distrivution'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deploy/distrivution'
  id: '__root__' | '/' | '/deploy/distrivution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy/distrivution': {
      id: '/deploy/distrivution'
      path: '/distrivution'
      fullPath: '/deploy/distrivution'
      preLoaderRoute: typeof DeployDistrivutionRouteImport
      parentRoute: typeof DeployRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
